//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.18 at 11:12:03 PM EDT 
//


package com.parsons.dao.model.test;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity(name = "TableOne")
@Table(name = "Table_One")
@Inheritance(strategy = InheritanceType.JOINED)
public class TableOne
{

    protected String tableOneId;
    protected String name;
    protected Timestamp createDate;
    protected List<TableTwo> tableTwoList;
    protected List<TableThree> tableThrees;

    @Id
    @Column(name = "table_one_id", length = 36)
    public String getTableOneId() {
        return tableOneId;
    }

    public void setTableOneId(String value) {
        this.tableOneId = value;
    }

    @Basic
    @Column(name = "name", length = 255)
    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    @Basic
    @Column(name = "create_date")
    public Timestamp getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Timestamp value) {
        this.createDate = value;
    }

    @OneToMany(targetEntity = TableTwo.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "table_one_id")
    public List<TableTwo> getTableTwoList() {
        if (tableTwoList == null) {
            tableTwoList = new ArrayList<TableTwo>();
        }
        return this.tableTwoList;
    }

    public void setTableTwoList(List<TableTwo> tableTwoList) {
        this.tableTwoList = tableTwoList;
    }

    @OneToMany(targetEntity = TableThree.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "table_one_id")
    public List<TableThree> getTableThrees() {
        if (tableThrees == null) {
        	tableThrees = new ArrayList<TableThree>();
        }
        return this.tableThrees;
    }

    public void setTableThrees(List<TableThree> tableThrees) {
        this.tableThrees = tableThrees;
    }

}
