//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.18 at 11:12:03 PM EDT 
//


package com.parsons.dao.model.test;

import java.sql.Timestamp;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity(name = "TableTwo")
@Table(name = "Table_Two")
@Inheritance(strategy = InheritanceType.JOINED)
public class TableTwo
{

    protected Integer tableTwoId;
    protected String name;
    protected Integer tableOneId;
    protected TableOne tableOne;
    protected String abbreviation;
    protected Timestamp createDate;

    @Id
    @Column(name = "table_two_id", scale = 0)
    @GeneratedValue(generator = "table_two_sequence", strategy = GenerationType.SEQUENCE)
    @SequenceGenerator(name = "table_two_sequence", sequenceName = "TABLE_TWO_SEQ")
    public Integer getTableTwoId() {
        return tableTwoId;
    }

    public void setTableTwoId(Integer value) {
        this.tableTwoId = value;
    }

    @Basic
    @Column(name = "name", length = 255)
    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    @Basic
    @Column(name = "table_one_id", length = 36)
    public Integer getTableOneId () {
        return tableOneId;
    }

    public void setTableOneId(Integer value) {
        this.tableOneId = value;
    }

    @ManyToOne(targetEntity = TableOne.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "table_one_id")
    public TableOne getTableOne() {
        return tableOne;
    }

    public void setTableOne(TableOne value) {
        this.tableOne = value;
    }

    @Basic
    @Column(name = "ABBREVIATION", length = 255)
    public String getAbbreviation() {
        return abbreviation;
    }

    public void setAbbreviation(String value) {
        this.abbreviation = value;
    }

    @Basic
    @Column(name = "create_date")
    public Timestamp getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Timestamp value) {
        this.createDate = value;
    }

}
