//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.18 at 11:12:03 PM EDT 
//


package com.hyperdao.model.test;

import java.sql.Timestamp;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity(name = "TableThree")
@Table(name = "Table_Three")
@Inheritance(strategy = InheritanceType.JOINED)
public class TableThree
{

    protected Integer tableThreeId;
    protected String name;
    protected String tableOneId;
    protected String tableOneIdAlternate;
    protected TableOne tableOne;
    protected TableOne tableOneAlternate;
    protected String abbreviation;
    protected Timestamp createDate;

    @Id
    @Column(name = "table_three_id", scale = 0)
    @GeneratedValue(generator = "table_Three_sequence", strategy = GenerationType.SEQUENCE)
    @SequenceGenerator(name = "table_Three_sequence", sequenceName = "TABLE_Three_SEQ")
    public Integer getTableThreeId() {
        return tableThreeId;
    }

    public void setTableThreeId(Integer value) {
        this.tableThreeId = value;
    }

    @Basic
    @Column(name = "name", length = 255)
    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    @Basic
    @Column(name = "table_one_id", length = 36)
    public String getTableOneId () {
        return tableOneId;
    }

    public void setTableOneId(String value) {
        this.tableOneId = value;
    }

    @ManyToOne(targetEntity = TableOne.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "table_one_id")
    public TableOne getTableOne() {
        return tableOne;
    }

    public void setTableOne(TableOne value) {
        this.tableOne = value;
    }
    
    @Basic
    @Column(name = "table_one_id_alternate", length = 36)
    public String getTableOneIdAlternate() {
		return tableOneIdAlternate;
	}

	public void setTableOneIdAlternate(String tableOneIdAlternate) {
		this.tableOneIdAlternate = tableOneIdAlternate;
	}

    @ManyToOne(targetEntity = TableOne.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "table_one_id_alternate", referencedColumnName = "table_one_id")
	public TableOne getTableOneAlternate() {
		return tableOneAlternate;
	}

	public void setTableOneAlternate(TableOne tableOneAlternate) {
		this.tableOneAlternate = tableOneAlternate;
	}

	@Basic
    @Column(name = "ABBREVIATION", length = 255)
    public String getAbbreviation() {
        return abbreviation;
    }

    public void setAbbreviation(String value) {
        this.abbreviation = value;
    }

    @Basic
    @Column(name = "create_date")
    public Timestamp getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Timestamp value) {
        this.createDate = value;
    }

}
